

(in-package :guicho-geometry)
(annot:enable-annot-syntax)

;; (defmethod bottom-of ((r 2drectangle))
;;   (slot-value (slot-value r 'v0) 'y))
;; (defmethod left-of ((r 2drectangle))
;;   (slot-value (slot-value r 'v0) 'x))
;; (defmethod right-of ((r 2drectangle))
;;   (slot-value (slot-value r 'v1) 'x))
;; (defmethod top-of ((r 2drectangle))
;;   (slot-value (slot-value r 'v1) 'y))

(define-permutation-methods intersects-p ((r 2drectangle) (s 2dsegment))
  (with-slots (v0 v1) r
    (with-slots (from to) s
      (let ((d (sub-vector to from)))
        (if (d= (x-of d) 0.0d0)
            (let* ((sl (d/ (x-of d) (y-of d)))
                   (xmin (d- (x-of v0) (x-of from)))
                   (xmax (d- (x-of v1) (x-of from)))
                   (xself (d- (x-of to) (x-of from)))
                   (rx (make-range xmin xmax))
                   (ymin-to-x (d* sl (d- (y-of v0) (y-of from))))
                   (ymax-to-x (d* sl (d- (y-of v1) (y-of from))))
                   (ry-to-x (make-range ymin-to-x ymax-to-x)))
              (intersects-p (region-product rx ry-to-x)
                            (make-range 0.0d0 xself)))
            (let* ((sl (d/ (y-of d) (x-of d)))
                   (ymin (d- (y-of v0) (y-of from)))
                   (ymax (d- (y-of v1) (y-of from)))
                   (yself (d- (y-of to) (y-of from)))
                   (ry (make-range ymin ymax))
                   (xmin-to-y (d* sl (d- (x-of v0) (x-of from))))
                   (xmax-to-y (d* sl (d- (x-of v1) (x-of from))))
                   (rx-to-y (make-range xmin-to-y xmax-to-y)))
              (intersects-p (region-product ry rx-to-y)
                            (make-range 0.0d0 yself))))))))


(define-permutation-methods intersects-p ((r 2drectangle) (s 2dline))
  (with-slots (v0 v1) r
    (with-slots (from to) s
      (let ((d (sub-vector to from)))
        (if (d= (x-of d) 0.0d0)
            (let* ((sl (d/ (x-of d) (y-of d)))
                   (xmin (d- (x-of v0) (x-of from)))
                   (xmax (d- (x-of v1) (x-of from)))
                   (rx (make-range xmin xmax))
                   (ymin-to-x (d* sl (d- (y-of v0) (y-of from))))
                   (ymax-to-x (d* sl (d- (y-of v1) (y-of from))))
                   (ry-to-x (make-range ymin-to-x ymax-to-x)))
              (intersects-p rx ry-to-x))
            (let* ((sl (d/ (y-of d) (x-of d)))
                   (ymin (d- (y-of v0) (y-of from)))
                   (ymax (d- (y-of v1) (y-of from)))
                   (ry (make-range ymin ymax))
                   (xmin-to-y (d* sl (d- (x-of v0) (x-of from))))
                   (xmax-to-y (d* sl (d- (x-of v1) (x-of from))))
                   (rx-to-y (make-range xmin-to-y xmax-to-y)))
              (intersects-p ry rx-to-y)))))))
